### PR TITLE
Cross compatibility script to upload ATmega2560

### PR DESCRIPTION
**Pull request by fabiomanz**
-> Issue #456 
-> Works with python 2 & 3
-> Works on Linux & Windows

### CODE REVIEW

**Review by uzi18 — APPROVED** [review]

**Comment by tve** [comment]
Thank you!

**Comment by uzi18** [comment]
@tve you didn't merge it?

**Comment by tve** [comment]
Oops, thanks for catching that! I hit the close&comment too fast and it didn't merge, grrrr.

**Comment by uzi18** [comment]
my PR also waiting to merge, i want to take some  good fixes from leodesigner repo next... and will prepare next PR with this

**Pull request merged**
