### PR TITLE
V2: Adding the console uart format support 

### PR DESCRIPTION
**Pull request by bitdump**
Some of the MCU use format other than 8N1.
Adding the support for other format.

Change compare to previous merge request V1:
- fix tab vs space in html.
- uart init now load the config from flash
- add code to migrate from old flash format.
  Which means it does not support 5 bits format. Who use 5 bits any way?

### CODE REVIEW

**Comment by Niwreg** [comment]
Is there a bin file i can test? I've never build the firmware myself and i'm not complete sure how to do this with pull requests and git  and all:)

**Comment by bitdump** [comment]
How to attach a binary file for testing the merge request? I have the binary file but I don't know how to upload it.

**Comment by tve** [comment]
PLace the bin file into a zip archive and drag that into the comment box....
I meant to set-up automated builds this evening but something pre-empted that. I'll try again tomorrow...

**Comment by bitdump** [comment]
[uart-format.zip](https://github.com/jeelabs/esp-link/files/481839/uart-format.zip)

OK, I just upload the binary file for testing.

**Comment by Niwreg** [comment]
Yes this is working for :) thanx!

**Comment by bitdump** [comment]
Thanks for the the test and feed back. Good to know it works for some one else as well。

**Comment by tve** [comment]
Thanks!

**Pull request merged**
