### PR TITLE
Fixes for windows and visual studio

### PR DESCRIPTION
**Pull request by brunnels**
Should still be fine on other OS.  Visual studio is just more picky on references.

### CODE REVIEW

**Comment by brunnels** [comment]
Last commit I actually meant "Restored ability to remove syslog from MODULES in Makefile"

**Comment by tve** [comment]
You're reverting what I did in https://github.com/jeelabs/esp-link/commit/ac92202ef6d82de87763c428087068fe5c41296c in order to try and support both esp-open-sdk with included SDK and without included SDK. How does your change improve that and what was wrong in the first place?

**Comment by brunnels** [comment]
I didn't realize it was reverting anything.  c_types.h is still included in esp8266,h so it wasn't removed.

I was just resolving what I'm seeing as errors for every c-type as undefined when using sdk-1.5.2 and visual studio.  Maybe an alternative is to have a different behavior when using the espressif sfk vs the esp-open-sdk?  Are there any benefits to using esp-open-sdk over the espressif sdk?

**Comment by tve** [comment]
I think I got all the stuff in other PRs/commits. Holler if not.

**Pull request closed without merging**
