### PR TITLE
Add missing baudrate settings.

### PR DESCRIPTION
**Pull request by hetii**
Hi.

I add missing baud-rate setting.
Minimal value start now from 300.

Best Regards.

### CODE REVIEW

**Comment by tve** [comment]
Thanks much!

**Comment by roesl** [comment]
Thanks  much  ! 

When will the changes included in the download Version of release V3.0 ?

**Comment by tve** [comment]
I'm trying to get a fresh alpha or beta release out this week, no promises though.

**Comment by roesl** [comment]
Thanks ! I will wait for the new release because I´m just a beginner with programming

**Pull request merged**
