### PR TITLE
Upgrade firmware from web interface

### PR DESCRIPTION
**Pull request by nemik**
This pull request enables firmware upgrades from within the web interface with an easy upload form.

### CODE REVIEW

**Comment by tve** [comment]
Very cool! What happens if you include the non-minified nanajax library and let the esp-link Makefile minify it? I assume it'll take a few more bytes, but this way there's not that cryptic blob in the source.

So far I've only read through the code, it'll take me a little to test it (busy with some other stuff I have to get done). Thanks much!

**Comment by nemik** [comment]
You know, it's not even an issue anymore. I dug deeper into what nanoajax was actually doing and just added it myself to ui.js. All that was missing is to put the file data from the form into the XHR's send() function.

To do that, I had to modify the ui.js's "ajaxReq" function to take that variable as a parameter. But to keep it from interfering with all the rest of the functions that depend on it, I just added that 'data' parameter at the end. The nice thing about JS is the other functions all still work because it just assigns null to that 'data' arg as it was before. So no other code has to change, firmware upgrade on UI still works, and no other dependencies exist now.

Give it a shot and hopefully you like it. Thanks again for this awesome project, it's so nice to work with because of how well-organized things are.

**Comment by harmeetsingh-work** [comment]
This seems to be nice feature, when can we expect this in release. :)

**Comment by tve** [comment]
@blackadmin did you test it?

**Comment by harmeetsingh-work** [comment]
@tve No, I have not.

**Pull request merged**
