### PR TITLE
Segment huge packets at TCP receive

### PR DESCRIPTION
**Pull request by cskarai**
Arduino is not able to receive huge packets, the input buffer is 128 byte.
The patch segments packet into smaller parts if required.

### CODE REVIEW

**Comment by tve** [comment]
This looks interesting, can you please add some comments to describe how it works or what it does? E.g. how are segments that need to be assembled identified?

**Comment by stramike** [comment]
@cskarai  could you please explain how to handle packets longer then 100 bytes? I'm currently receiving only the first 100 bytes of the message. How am I supposed to handle the other parts?
Any help would be really appreciated.

**Comment by congrio** [comment]
> @cskarai could you please explain how to handle packets longer then 100 bytes? I'm currently receiving only the first 100 bytes of the message. How am I supposed to handle the other parts?
> Any help would be really appreciated.

Any info on how to get more than 100 bytes? thanks!

**Comment by uzi18** [comment]
you need patched ELClient library to use it or implement your own communication functions with SLIP packets

**Pull request merged**
